#include "Matrix.hpp"

int main() {
	try {

	} catch (const std::exception &e) {
		std::cout << "Exception:" << e.what() << std::endl;
	}

	return 0;
}
